### ISSUE TITLE
Permission to abstract DrupalCheck

### ISSUE THREAD

**Issue by mikebell** [eojthebrave/isthissitebuiltwithdrupal_com#1]
Hi Joe,

Thanks for this! I'd like to include this as part of a Drupal project I'm working on at the moment. Would you allow me to abstract the DrupalCheck class into it's own composer package?

**Comment by eojthebrave** [comment]
That would be fine with me. If you do, and and then let me know when you're done, I can update things on my end to use the new class so we're not duplicating efforts in the future.

**Comment by mikebell** [comment]
I've created this - https://github.com/mikebell/drupalcheck

There are 3 notable changes:
1. Updated guzzle which made a couple of things redundant, see comments in file.
2. Added 2 new tests based on headers sent via the server.
3. Re worked the inDrupal function so it runs all tests regardless of a pass, this way you can see what passed and failed in the results array and act on it if required.

I'm happy to publish to packagist if you give me the ok.

**Comment by eojthebrave** [comment]
👍  looks good to me. Go for it.

**Comment by mikebell** [comment]
This is now available via https://packagist.org/packages/mikebell/drupalcheck
